version: '3'

# note: please specify all the [adminName] and [password] fields

services:

  router:
    image: mongo:latest
    container_name: smtet-mongo-router
    environment:
        - MONGO_INITDB_ROOT_USERNAME=[adminName]
        - MONGO_INITDB_ROOT_PASSWORD=[password]
    ports:
      - "12702:27017"
    volumes:
      - "/workspace/www/smtet-mongos/router/mongos.conf:/etc/mongos.conf"
      - "/workspace/www/smtet-mongos/common/mongo-keyfile:/opt/mongo/mongo-keyfile"
      - "/workspace/downloadCenter:/workspace/downloadCenter"
    command:
      - mongos
      - --config
      - /etc/mongos.conf
    networks:
      smtet_net:
        ipv4_address: 172.22.0.100

  config1:
    image: mongo:latest
    container_name: smtet-mongo-config1
    environment:
        - MONGO_INITDB_ROOT_USERNAME=[adminName]
        - MONGO_INITDB_ROOT_PASSWORD=[password]
    expose:
      - "27017"
    volumes:
      - "/workspace/www/smtet-mongos/configServer/mongod-c1.conf:/etc/mongod.conf"
      - "/workspace/www/smtet-mongos/common/mongo-keyfile:/opt/mongo/mongo-keyfile"
      - "/workspace/downloadCenter:/workspace/downloadCenter"
    command:
      - --config
      - /etc/mongod.conf
    networks:
      smtet_net:
        ipv4_address: 172.22.0.101

  config2:
    image: mongo:latest
    container_name: smtet-mongo-config2
    environment:
        - MONGO_INITDB_ROOT_USERNAME=[adminName]
        - MONGO_INITDB_ROOT_PASSWORD=[password]
    expose:
      - "27017"
    volumes:
      - "/workspace/www/smtet-mongos/configServer/mongod-c2.conf:/etc/mongod.conf"
      - "/workspace/www/smtet-mongos/common/mongo-keyfile:/opt/mongo/mongo-keyfile"
      - "/workspace/downloadCenter:/workspace/downloadCenter"
    command:
      - --config
      - /etc/mongod.conf
    networks:
      smtet_net:
        ipv4_address: 172.22.0.102

  config3:
    image: mongo:latest
    container_name: smtet-mongo-config3
    environment:
        - MONGO_INITDB_ROOT_USERNAME=[adminName]
        - MONGO_INITDB_ROOT_PASSWORD=[password]
    expose:
      - "27017"
    volumes:
      - "/workspace/www/smtet-mongos/configServer/mongod-c3.conf:/etc/mongod.conf"
      - "/workspace/www/smtet-mongos/common/mongo-keyfile:/opt/mongo/mongo-keyfile"
      - "/workspace/downloadCenter:/workspace/downloadCenter"
    command:
      - --config
      - /etc/mongod.conf
    networks:
      smtet_net:
        ipv4_address: 172.22.0.103

  shard1:
    image: mongo:latest
    container_name: smtet-mongo-shard1
    environment:
        - MONGO_INITDB_ROOT_USERNAME=[adminName]
        - MONGO_INITDB_ROOT_PASSWORD=[password]
    expose:
      - "27017"
    volumes:
      - "/workspace/www/smtet-mongos/shards/mongod-c1.conf:/etc/mongod.conf"
      - "/workspace/www/smtet-mongos/common/mongo-keyfile:/opt/mongo/mongo-keyfile"
      - "/workspace/downloadCenter:/workspace/downloadCenter"
    command:
      - --config
      - /etc/mongod.conf
    networks:
      smtet_net:
        ipv4_address: 172.22.0.110

  shard2:
    image: mongo:latest
    container_name: smtet-mongo-shard2
    environment:
        - MONGO_INITDB_ROOT_USERNAME=[adminName]
        - MONGO_INITDB_ROOT_PASSWORD=[password]
    expose:
      - "27017"
    volumes:
      - "/workspace/www/smtet-mongos/shards/mongod-c2.conf:/etc/mongod.conf"
      - "/workspace/www/smtet-mongos/common/mongo-keyfile:/opt/mongo/mongo-keyfile"
      - "/workspace/downloadCenter:/workspace/downloadCenter"
    command:
      - --config
      - /etc/mongod.conf
    networks:
      smtet_net:
        ipv4_address: 172.22.0.111

networks:
  smtet_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16