FROM node:alpine
LABEL maintainer="Valroad <valorad@outlook.com>"

ADD ./dist /www/smart-eatout/
ADD ./package.dist.json /www/smart-eatout/package.json

WORKDIR /www/smart-eatout

RUN echo " --- Collecting node modules --- " \
 # node module collection
 && npm install \
 && npm cache clean --force

VOLUME ["/www/smart-eatout/configs"]

EXPOSE 3000

CMD npm run start && /bin/sh
